---
name: CI

on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - v*.*.*
  pull_request:

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: fish-actions/install-fish@v1.1.0

      - uses: fish-actions/fisher@v1.0.0
        with:
          plugins: ilancosman/clownfish $GITHUB_WORKSPACE

      - uses: fish-actions/littlecheck@v1
        with:
          files: $GITHUB_WORKSPACE/tests/**

  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actionsx/prettier@v2
        with:
          args: --check .

  super-linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: github/super-linter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_MD: true
          VALIDATE_YAML: true
